# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: obb/markets.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'obb/markets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11obb/markets.proto\x12\x03obb\"6\n\x17\x41vailableMarketsRequest\x12\x1b\n\tevent_urn\x18\x01 \x01(\tR\x08\x65ventUrn\"J\n\x18\x41vailableMarketsResponse\x12.\n\x07markets\x18\x01 \x03(\x0b\x32\x14.obb.AvailableMarketR\x07markets\"N\n\x0f\x41vailableMarket\x12\x1b\n\tmarket_id\x18\x01 \x01(\rR\x08marketId\x12\x1e\n\nspecifiers\x18\x02 \x01(\tR\nspecifiersB5\n\rcom.oddin.obbZ$github.com/oddin-gg/obbschema/go/obbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'obb.markets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.oddin.obbZ$github.com/oddin-gg/obbschema/go/obb'
  _globals['_AVAILABLEMARKETSREQUEST']._serialized_start=26
  _globals['_AVAILABLEMARKETSREQUEST']._serialized_end=80
  _globals['_AVAILABLEMARKETSRESPONSE']._serialized_start=82
  _globals['_AVAILABLEMARKETSRESPONSE']._serialized_end=156
  _globals['_AVAILABLEMARKET']._serialized_start=158
  _globals['_AVAILABLEMARKET']._serialized_end=236
# @@protoc_insertion_point(module_scope)
