# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from obb_schema.obb import markets_pb2 as obb_dot_markets__pb2
from obb_schema.obb import popular_pb2 as obb_dot_popular__pb2
from obb_schema.obb import session_pb2 as obb_dot_session__pb2


class obbStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AvailableMarkets = channel.unary_unary(
                '/obb.obb/AvailableMarkets',
                request_serializer=obb_dot_markets__pb2.AvailableMarketsRequest.SerializeToString,
                response_deserializer=obb_dot_markets__pb2.AvailableMarketsResponse.FromString,
                _registered_method=True)
        self.SessionCreate = channel.unary_unary(
                '/obb.obb/SessionCreate',
                request_serializer=obb_dot_session__pb2.SessionCreateRequest.SerializeToString,
                response_deserializer=obb_dot_session__pb2.SessionCreateResponse.FromString,
                _registered_method=True)
        self.SessionInfo = channel.unary_unary(
                '/obb.obb/SessionInfo',
                request_serializer=obb_dot_session__pb2.SessionInfoRequest.SerializeToString,
                response_deserializer=obb_dot_session__pb2.SessionInfoResponse.FromString,
                _registered_method=True)
        self.PopularCombination = channel.unary_unary(
                '/obb.obb/PopularCombination',
                request_serializer=obb_dot_popular__pb2.PopularCombinationRequest.SerializeToString,
                response_deserializer=obb_dot_popular__pb2.PopularCombinationResponse.FromString,
                _registered_method=True)


class obbServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AvailableMarkets(self, request, context):
        """Used to retrieve a list of available markets for a given event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionCreate(self, request, context):
        """Used for session creation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionInfo(self, request, context):
        """Used for extraction info about desired session based on session id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PopularCombination(self, request, context):
        """Used to get popular combinations of selections.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_obbServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AvailableMarkets': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableMarkets,
                    request_deserializer=obb_dot_markets__pb2.AvailableMarketsRequest.FromString,
                    response_serializer=obb_dot_markets__pb2.AvailableMarketsResponse.SerializeToString,
            ),
            'SessionCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionCreate,
                    request_deserializer=obb_dot_session__pb2.SessionCreateRequest.FromString,
                    response_serializer=obb_dot_session__pb2.SessionCreateResponse.SerializeToString,
            ),
            'SessionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionInfo,
                    request_deserializer=obb_dot_session__pb2.SessionInfoRequest.FromString,
                    response_serializer=obb_dot_session__pb2.SessionInfoResponse.SerializeToString,
            ),
            'PopularCombination': grpc.unary_unary_rpc_method_handler(
                    servicer.PopularCombination,
                    request_deserializer=obb_dot_popular__pb2.PopularCombinationRequest.FromString,
                    response_serializer=obb_dot_popular__pb2.PopularCombinationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'obb.obb', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('obb.obb', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class obb(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AvailableMarkets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obb.obb/AvailableMarkets',
            obb_dot_markets__pb2.AvailableMarketsRequest.SerializeToString,
            obb_dot_markets__pb2.AvailableMarketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obb.obb/SessionCreate',
            obb_dot_session__pb2.SessionCreateRequest.SerializeToString,
            obb_dot_session__pb2.SessionCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obb.obb/SessionInfo',
            obb_dot_session__pb2.SessionInfoRequest.SerializeToString,
            obb_dot_session__pb2.SessionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PopularCombination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obb.obb/PopularCombination',
            obb_dot_popular__pb2.PopularCombinationRequest.SerializeToString,
            obb_dot_popular__pb2.PopularCombinationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
