// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.3
// source: obb/markets.proto

package obb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AvailableMarketsRequest is used as request for Markets RPC call
type AvailableMarketsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Event ID URN - e.g "od:match:xx"
	EventUrn string `protobuf:"bytes,1,opt,name=event_urn,json=eventUrn,proto3" json:"event_urn,omitempty"`
}

func (x *AvailableMarketsRequest) Reset() {
	*x = AvailableMarketsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obb_markets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableMarketsRequest) ProtoMessage() {}

func (x *AvailableMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obb_markets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableMarketsRequest.ProtoReflect.Descriptor instead.
func (*AvailableMarketsRequest) Descriptor() ([]byte, []int) {
	return file_obb_markets_proto_rawDescGZIP(), []int{0}
}

func (x *AvailableMarketsRequest) GetEventUrn() string {
	if x != nil {
		return x.EventUrn
	}
	return ""
}

// AvailableMarketsResponse is used as response for AvailableMarketsRequest RPC call
type AvailableMarketsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of available markets
	Markets []*AvailableMarket `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
}

func (x *AvailableMarketsResponse) Reset() {
	*x = AvailableMarketsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obb_markets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableMarketsResponse) ProtoMessage() {}

func (x *AvailableMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obb_markets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableMarketsResponse.ProtoReflect.Descriptor instead.
func (*AvailableMarketsResponse) Descriptor() ([]byte, []int) {
	return file_obb_markets_proto_rawDescGZIP(), []int{1}
}

func (x *AvailableMarketsResponse) GetMarkets() []*AvailableMarket {
	if x != nil {
		return x.Markets
	}
	return nil
}

type AvailableMarket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID using the same values as our odds feed in XML.
	MarketId uint32 `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// The specifier is using the same values as our odds feed in XML.
	// Example: "variant=way:three|way=three|map=1"
	Specifiers string `protobuf:"bytes,2,opt,name=specifiers,proto3" json:"specifiers,omitempty"`
}

func (x *AvailableMarket) Reset() {
	*x = AvailableMarket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obb_markets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableMarket) ProtoMessage() {}

func (x *AvailableMarket) ProtoReflect() protoreflect.Message {
	mi := &file_obb_markets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableMarket.ProtoReflect.Descriptor instead.
func (*AvailableMarket) Descriptor() ([]byte, []int) {
	return file_obb_markets_proto_rawDescGZIP(), []int{2}
}

func (x *AvailableMarket) GetMarketId() uint32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *AvailableMarket) GetSpecifiers() string {
	if x != nil {
		return x.Specifiers
	}
	return ""
}

var File_obb_markets_proto protoreflect.FileDescriptor

var file_obb_markets_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x62, 0x62, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f, 0x62, 0x62, 0x22, 0x36, 0x0a, 0x17, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x72, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6e,
	0x22, 0x4a, 0x0a, 0x18, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6f, 0x62, 0x62, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x52, 0x07, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x4e, 0x0a, 0x0f,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x42, 0x35, 0x0a, 0x0d,
	0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x64, 0x64, 0x69, 0x6e, 0x2e, 0x6f, 0x62, 0x62, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x64, 0x64, 0x69, 0x6e, 0x2d,
	0x67, 0x67, 0x2f, 0x6f, 0x62, 0x62, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x67, 0x6f, 0x2f,
	0x6f, 0x62, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_obb_markets_proto_rawDescOnce sync.Once
	file_obb_markets_proto_rawDescData = file_obb_markets_proto_rawDesc
)

func file_obb_markets_proto_rawDescGZIP() []byte {
	file_obb_markets_proto_rawDescOnce.Do(func() {
		file_obb_markets_proto_rawDescData = protoimpl.X.CompressGZIP(file_obb_markets_proto_rawDescData)
	})
	return file_obb_markets_proto_rawDescData
}

var file_obb_markets_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_obb_markets_proto_goTypes = []interface{}{
	(*AvailableMarketsRequest)(nil),  // 0: obb.AvailableMarketsRequest
	(*AvailableMarketsResponse)(nil), // 1: obb.AvailableMarketsResponse
	(*AvailableMarket)(nil),          // 2: obb.AvailableMarket
}
var file_obb_markets_proto_depIdxs = []int32{
	2, // 0: obb.AvailableMarketsResponse.markets:type_name -> obb.AvailableMarket
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_obb_markets_proto_init() }
func file_obb_markets_proto_init() {
	if File_obb_markets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_obb_markets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableMarketsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obb_markets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableMarketsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obb_markets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableMarket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_obb_markets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_obb_markets_proto_goTypes,
		DependencyIndexes: file_obb_markets_proto_depIdxs,
		MessageInfos:      file_obb_markets_proto_msgTypes,
	}.Build()
	File_obb_markets_proto = out.File
	file_obb_markets_proto_rawDesc = nil
	file_obb_markets_proto_goTypes = nil
	file_obb_markets_proto_depIdxs = nil
}
