// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: obb/popular.proto

package obb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PopularCombinationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event ID URN - e.g "od:match:xx"
	EventId       string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularCombinationRequest) Reset() {
	*x = PopularCombinationRequest{}
	mi := &file_obb_popular_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularCombinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularCombinationRequest) ProtoMessage() {}

func (x *PopularCombinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obb_popular_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularCombinationRequest.ProtoReflect.Descriptor instead.
func (*PopularCombinationRequest) Descriptor() ([]byte, []int) {
	return file_obb_popular_proto_rawDescGZIP(), []int{0}
}

func (x *PopularCombinationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type PopularCombinationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Popular selection combinations for the event, ready to be used
	// in SessionCreateRequest without further processing.
	Combinations  []*PopularCombination `protobuf:"bytes,2,rep,name=combinations,proto3" json:"combinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularCombinationResponse) Reset() {
	*x = PopularCombinationResponse{}
	mi := &file_obb_popular_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularCombinationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularCombinationResponse) ProtoMessage() {}

func (x *PopularCombinationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obb_popular_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularCombinationResponse.ProtoReflect.Descriptor instead.
func (*PopularCombinationResponse) Descriptor() ([]byte, []int) {
	return file_obb_popular_proto_rawDescGZIP(), []int{1}
}

func (x *PopularCombinationResponse) GetCombinations() []*PopularCombination {
	if x != nil {
		return x.Combinations
	}
	return nil
}

type PopularCombination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Selections forming the combination, in the same format as
	// SessionCreateRequest.selection_ids:
	// "<event_id>/<market_id>/<outcome_id>?<market_specifier>"
	// Example: "od:match:1234/1/1?map=1&way=two"
	SelectionIds []string `protobuf:"bytes,1,rep,name=selection_ids,json=selectionIds,proto3" json:"selection_ids,omitempty"`
	// Total odds for the whole combination.
	// Odds multiplied by 10000 and rounded to uint value.
	Odds uint64 `protobuf:"varint,2,opt,name=odds,proto3" json:"odds,omitempty"`
	// Raw probability of the combination (value between 0.0 and 1.0).
	// This is the combined probability of all selections before margin is applied.
	RawProbability float64 `protobuf:"fixed64,3,opt,name=raw_probability,json=rawProbability,proto3" json:"raw_probability,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PopularCombination) Reset() {
	*x = PopularCombination{}
	mi := &file_obb_popular_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularCombination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularCombination) ProtoMessage() {}

func (x *PopularCombination) ProtoReflect() protoreflect.Message {
	mi := &file_obb_popular_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularCombination.ProtoReflect.Descriptor instead.
func (*PopularCombination) Descriptor() ([]byte, []int) {
	return file_obb_popular_proto_rawDescGZIP(), []int{2}
}

func (x *PopularCombination) GetSelectionIds() []string {
	if x != nil {
		return x.SelectionIds
	}
	return nil
}

func (x *PopularCombination) GetOdds() uint64 {
	if x != nil {
		return x.Odds
	}
	return 0
}

func (x *PopularCombination) GetRawProbability() float64 {
	if x != nil {
		return x.RawProbability
	}
	return 0
}

var File_obb_popular_proto protoreflect.FileDescriptor

const file_obb_popular_proto_rawDesc = "" +
	"\n" +
	"\x11obb/popular.proto\x12\x03obb\"6\n" +
	"\x19PopularCombinationRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"h\n" +
	"\x1aPopularCombinationResponse\x12;\n" +
	"\fcombinations\x18\x02 \x03(\v2\x17.obb.PopularCombinationR\fcombinationsJ\x04\b\x01\x10\x02R\amarkets\"v\n" +
	"\x12PopularCombination\x12#\n" +
	"\rselection_ids\x18\x01 \x03(\tR\fselectionIds\x12\x12\n" +
	"\x04odds\x18\x02 \x01(\x04R\x04odds\x12'\n" +
	"\x0fraw_probability\x18\x03 \x01(\x01R\x0erawProbabilityB5\n" +
	"\rcom.oddin.obbZ$github.com/oddin-gg/obbschema/go/obbb\x06proto3"

var (
	file_obb_popular_proto_rawDescOnce sync.Once
	file_obb_popular_proto_rawDescData []byte
)

func file_obb_popular_proto_rawDescGZIP() []byte {
	file_obb_popular_proto_rawDescOnce.Do(func() {
		file_obb_popular_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_obb_popular_proto_rawDesc), len(file_obb_popular_proto_rawDesc)))
	})
	return file_obb_popular_proto_rawDescData
}

var file_obb_popular_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_obb_popular_proto_goTypes = []any{
	(*PopularCombinationRequest)(nil),  // 0: obb.PopularCombinationRequest
	(*PopularCombinationResponse)(nil), // 1: obb.PopularCombinationResponse
	(*PopularCombination)(nil),         // 2: obb.PopularCombination
}
var file_obb_popular_proto_depIdxs = []int32{
	2, // 0: obb.PopularCombinationResponse.combinations:type_name -> obb.PopularCombination
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_obb_popular_proto_init() }
func file_obb_popular_proto_init() {
	if File_obb_popular_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_obb_popular_proto_rawDesc), len(file_obb_popular_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_obb_popular_proto_goTypes,
		DependencyIndexes: file_obb_popular_proto_depIdxs,
		MessageInfos:      file_obb_popular_proto_msgTypes,
	}.Build()
	File_obb_popular_proto = out.File
	file_obb_popular_proto_goTypes = nil
	file_obb_popular_proto_depIdxs = nil
}
