// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: obb/service.proto

package obb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_obb_service_proto protoreflect.FileDescriptor

const file_obb_service_proto_rawDesc = "" +
	"\n" +
	"\x11obb/service.proto\x12\x03obb\x1a\x11obb/markets.proto\x1a\x11obb/popular.proto\x1a\x11obb/session.proto2\xb7\x02\n" +
	"\x03obb\x12O\n" +
	"\x10AvailableMarkets\x12\x1c.obb.AvailableMarketsRequest\x1a\x1d.obb.AvailableMarketsResponse\x12F\n" +
	"\rSessionCreate\x12\x19.obb.SessionCreateRequest\x1a\x1a.obb.SessionCreateResponse\x12@\n" +
	"\vSessionInfo\x12\x17.obb.SessionInfoRequest\x1a\x18.obb.SessionInfoResponse\x12U\n" +
	"\x12PopularCombination\x12\x1e.obb.PopularCombinationRequest\x1a\x1f.obb.PopularCombinationResponseB5\n" +
	"\rcom.oddin.obbZ$github.com/oddin-gg/obbschema/go/obbb\x06proto3"

var file_obb_service_proto_goTypes = []any{
	(*AvailableMarketsRequest)(nil),    // 0: obb.AvailableMarketsRequest
	(*SessionCreateRequest)(nil),       // 1: obb.SessionCreateRequest
	(*SessionInfoRequest)(nil),         // 2: obb.SessionInfoRequest
	(*PopularCombinationRequest)(nil),  // 3: obb.PopularCombinationRequest
	(*AvailableMarketsResponse)(nil),   // 4: obb.AvailableMarketsResponse
	(*SessionCreateResponse)(nil),      // 5: obb.SessionCreateResponse
	(*SessionInfoResponse)(nil),        // 6: obb.SessionInfoResponse
	(*PopularCombinationResponse)(nil), // 7: obb.PopularCombinationResponse
}
var file_obb_service_proto_depIdxs = []int32{
	0, // 0: obb.obb.AvailableMarkets:input_type -> obb.AvailableMarketsRequest
	1, // 1: obb.obb.SessionCreate:input_type -> obb.SessionCreateRequest
	2, // 2: obb.obb.SessionInfo:input_type -> obb.SessionInfoRequest
	3, // 3: obb.obb.PopularCombination:input_type -> obb.PopularCombinationRequest
	4, // 4: obb.obb.AvailableMarkets:output_type -> obb.AvailableMarketsResponse
	5, // 5: obb.obb.SessionCreate:output_type -> obb.SessionCreateResponse
	6, // 6: obb.obb.SessionInfo:output_type -> obb.SessionInfoResponse
	7, // 7: obb.obb.PopularCombination:output_type -> obb.PopularCombinationResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_obb_service_proto_init() }
func file_obb_service_proto_init() {
	if File_obb_service_proto != nil {
		return
	}
	file_obb_markets_proto_init()
	file_obb_popular_proto_init()
	file_obb_session_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_obb_service_proto_rawDesc), len(file_obb_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_obb_service_proto_goTypes,
		DependencyIndexes: file_obb_service_proto_depIdxs,
	}.Build()
	File_obb_service_proto = out.File
	file_obb_service_proto_goTypes = nil
	file_obb_service_proto_depIdxs = nil
}
