// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: obb/service.proto

package obb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ObbClient is the client API for Obb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObbClient interface {
	// Used to retrieve a list of available markets for a given event.
	AvailableMarkets(ctx context.Context, in *AvailableMarketsRequest, opts ...grpc.CallOption) (*AvailableMarketsResponse, error)
	// Used for session creation.
	SessionCreate(ctx context.Context, in *SessionCreateRequest, opts ...grpc.CallOption) (*SessionCreateResponse, error)
	// Used for extraction info about desired session based on session id.
	SessionInfo(ctx context.Context, in *SessionInfoRequest, opts ...grpc.CallOption) (*SessionInfoResponse, error)
	// Used to get popular combinations of selections.
	PopularCombination(ctx context.Context, in *PopularCombinationRequest, opts ...grpc.CallOption) (*PopularCombinationResponse, error)
}

type obbClient struct {
	cc grpc.ClientConnInterface
}

func NewObbClient(cc grpc.ClientConnInterface) ObbClient {
	return &obbClient{cc}
}

func (c *obbClient) AvailableMarkets(ctx context.Context, in *AvailableMarketsRequest, opts ...grpc.CallOption) (*AvailableMarketsResponse, error) {
	out := new(AvailableMarketsResponse)
	err := c.cc.Invoke(ctx, "/obb.obb/AvailableMarkets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *obbClient) SessionCreate(ctx context.Context, in *SessionCreateRequest, opts ...grpc.CallOption) (*SessionCreateResponse, error) {
	out := new(SessionCreateResponse)
	err := c.cc.Invoke(ctx, "/obb.obb/SessionCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *obbClient) SessionInfo(ctx context.Context, in *SessionInfoRequest, opts ...grpc.CallOption) (*SessionInfoResponse, error) {
	out := new(SessionInfoResponse)
	err := c.cc.Invoke(ctx, "/obb.obb/SessionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *obbClient) PopularCombination(ctx context.Context, in *PopularCombinationRequest, opts ...grpc.CallOption) (*PopularCombinationResponse, error) {
	out := new(PopularCombinationResponse)
	err := c.cc.Invoke(ctx, "/obb.obb/PopularCombination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObbServer is the server API for Obb service.
// All implementations must embed UnimplementedObbServer
// for forward compatibility
type ObbServer interface {
	// Used to retrieve a list of available markets for a given event.
	AvailableMarkets(context.Context, *AvailableMarketsRequest) (*AvailableMarketsResponse, error)
	// Used for session creation.
	SessionCreate(context.Context, *SessionCreateRequest) (*SessionCreateResponse, error)
	// Used for extraction info about desired session based on session id.
	SessionInfo(context.Context, *SessionInfoRequest) (*SessionInfoResponse, error)
	// Used to get popular combinations of selections.
	PopularCombination(context.Context, *PopularCombinationRequest) (*PopularCombinationResponse, error)
	mustEmbedUnimplementedObbServer()
}

// UnimplementedObbServer must be embedded to have forward compatible implementations.
type UnimplementedObbServer struct {
}

func (UnimplementedObbServer) AvailableMarkets(context.Context, *AvailableMarketsRequest) (*AvailableMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AvailableMarkets not implemented")
}
func (UnimplementedObbServer) SessionCreate(context.Context, *SessionCreateRequest) (*SessionCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionCreate not implemented")
}
func (UnimplementedObbServer) SessionInfo(context.Context, *SessionInfoRequest) (*SessionInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionInfo not implemented")
}
func (UnimplementedObbServer) PopularCombination(context.Context, *PopularCombinationRequest) (*PopularCombinationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PopularCombination not implemented")
}
func (UnimplementedObbServer) mustEmbedUnimplementedObbServer() {}

// UnsafeObbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObbServer will
// result in compilation errors.
type UnsafeObbServer interface {
	mustEmbedUnimplementedObbServer()
}

func RegisterObbServer(s grpc.ServiceRegistrar, srv ObbServer) {
	s.RegisterService(&Obb_ServiceDesc, srv)
}

func _Obb_AvailableMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObbServer).AvailableMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obb.obb/AvailableMarkets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObbServer).AvailableMarkets(ctx, req.(*AvailableMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Obb_SessionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObbServer).SessionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obb.obb/SessionCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObbServer).SessionCreate(ctx, req.(*SessionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Obb_SessionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObbServer).SessionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obb.obb/SessionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObbServer).SessionInfo(ctx, req.(*SessionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Obb_PopularCombination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopularCombinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObbServer).PopularCombination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obb.obb/PopularCombination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObbServer).PopularCombination(ctx, req.(*PopularCombinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Obb_ServiceDesc is the grpc.ServiceDesc for Obb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Obb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "obb.obb",
	HandlerType: (*ObbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AvailableMarkets",
			Handler:    _Obb_AvailableMarkets_Handler,
		},
		{
			MethodName: "SessionCreate",
			Handler:    _Obb_SessionCreate_Handler,
		},
		{
			MethodName: "SessionInfo",
			Handler:    _Obb_SessionInfo_Handler,
		},
		{
			MethodName: "PopularCombination",
			Handler:    _Obb_PopularCombination_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "obb/service.proto",
}
