// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: obb/settings.proto

package obb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether OBB is enabled for the client.
	ObbEnabled    bool `protobuf:"varint,1,opt,name=ObbEnabled,proto3" json:"ObbEnabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSettings) Reset() {
	*x = ClientSettings{}
	mi := &file_obb_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSettings) ProtoMessage() {}

func (x *ClientSettings) ProtoReflect() protoreflect.Message {
	mi := &file_obb_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSettings.ProtoReflect.Descriptor instead.
func (*ClientSettings) Descriptor() ([]byte, []int) {
	return file_obb_settings_proto_rawDescGZIP(), []int{0}
}

func (x *ClientSettings) GetObbEnabled() bool {
	if x != nil {
		return x.ObbEnabled
	}
	return false
}

type GetClientSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientSettingsRequest) Reset() {
	*x = GetClientSettingsRequest{}
	mi := &file_obb_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientSettingsRequest) ProtoMessage() {}

func (x *GetClientSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obb_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetClientSettingsRequest) Descriptor() ([]byte, []int) {
	return file_obb_settings_proto_rawDescGZIP(), []int{1}
}

func (x *GetClientSettingsRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetClientSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Settings      *ClientSettings        `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientSettingsResponse) Reset() {
	*x = GetClientSettingsResponse{}
	mi := &file_obb_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientSettingsResponse) ProtoMessage() {}

func (x *GetClientSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obb_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetClientSettingsResponse) Descriptor() ([]byte, []int) {
	return file_obb_settings_proto_rawDescGZIP(), []int{2}
}

func (x *GetClientSettingsResponse) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GetClientSettingsResponse) GetSettings() *ClientSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetClientSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Settings      *ClientSettings        `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClientSettingsRequest) Reset() {
	*x = SetClientSettingsRequest{}
	mi := &file_obb_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClientSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClientSettingsRequest) ProtoMessage() {}

func (x *SetClientSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obb_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClientSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetClientSettingsRequest) Descriptor() ([]byte, []int) {
	return file_obb_settings_proto_rawDescGZIP(), []int{3}
}

func (x *SetClientSettingsRequest) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *SetClientSettingsRequest) GetSettings() *ClientSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetClientSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Settings      *ClientSettings        `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClientSettingsResponse) Reset() {
	*x = SetClientSettingsResponse{}
	mi := &file_obb_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClientSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClientSettingsResponse) ProtoMessage() {}

func (x *SetClientSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obb_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClientSettingsResponse.ProtoReflect.Descriptor instead.
func (*SetClientSettingsResponse) Descriptor() ([]byte, []int) {
	return file_obb_settings_proto_rawDescGZIP(), []int{4}
}

func (x *SetClientSettingsResponse) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *SetClientSettingsResponse) GetSettings() *ClientSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ListClientSettingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, only clients with OBB enabled will be returned.
	FilterObbEnabledOnly bool `protobuf:"varint,1,opt,name=filter_obb_enabled_only,json=filterObbEnabledOnly,proto3" json:"filter_obb_enabled_only,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListClientSettingsRequest) Reset() {
	*x = ListClientSettingsRequest{}
	mi := &file_obb_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientSettingsRequest) ProtoMessage() {}

func (x *ListClientSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obb_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientSettingsRequest.ProtoReflect.Descriptor instead.
func (*ListClientSettingsRequest) Descriptor() ([]byte, []int) {
	return file_obb_settings_proto_rawDescGZIP(), []int{5}
}

func (x *ListClientSettingsRequest) GetFilterObbEnabledOnly() bool {
	if x != nil {
		return x.FilterObbEnabledOnly
	}
	return false
}

type ListClientSettingsResponse struct {
	state          protoimpl.MessageState                           `protogen:"open.v1"`
	ClientSettings []*ListClientSettingsResponse_ClientSettingsPair `protobuf:"bytes,1,rep,name=client_settings,json=clientSettings,proto3" json:"client_settings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListClientSettingsResponse) Reset() {
	*x = ListClientSettingsResponse{}
	mi := &file_obb_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientSettingsResponse) ProtoMessage() {}

func (x *ListClientSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obb_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientSettingsResponse.ProtoReflect.Descriptor instead.
func (*ListClientSettingsResponse) Descriptor() ([]byte, []int) {
	return file_obb_settings_proto_rawDescGZIP(), []int{6}
}

func (x *ListClientSettingsResponse) GetClientSettings() []*ListClientSettingsResponse_ClientSettingsPair {
	if x != nil {
		return x.ClientSettings
	}
	return nil
}

// Pair of client ID and their settings.
type ListClientSettingsResponse_ClientSettingsPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Settings      *ClientSettings        `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientSettingsResponse_ClientSettingsPair) Reset() {
	*x = ListClientSettingsResponse_ClientSettingsPair{}
	mi := &file_obb_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientSettingsResponse_ClientSettingsPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientSettingsResponse_ClientSettingsPair) ProtoMessage() {}

func (x *ListClientSettingsResponse_ClientSettingsPair) ProtoReflect() protoreflect.Message {
	mi := &file_obb_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientSettingsResponse_ClientSettingsPair.ProtoReflect.Descriptor instead.
func (*ListClientSettingsResponse_ClientSettingsPair) Descriptor() ([]byte, []int) {
	return file_obb_settings_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ListClientSettingsResponse_ClientSettingsPair) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ListClientSettingsResponse_ClientSettingsPair) GetSettings() *ClientSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_obb_settings_proto protoreflect.FileDescriptor

const file_obb_settings_proto_rawDesc = "" +
	"\n" +
	"\x12obb/settings.proto\x12\x03obb\"0\n" +
	"\x0eClientSettings\x12\x1e\n" +
	"\n" +
	"ObbEnabled\x18\x01 \x01(\bR\n" +
	"ObbEnabled\"7\n" +
	"\x18GetClientSettingsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\"i\n" +
	"\x19GetClientSettingsResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12/\n" +
	"\bsettings\x18\x02 \x01(\v2\x13.obb.ClientSettingsR\bsettings\"h\n" +
	"\x18SetClientSettingsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12/\n" +
	"\bsettings\x18\x02 \x01(\v2\x13.obb.ClientSettingsR\bsettings\"i\n" +
	"\x19SetClientSettingsResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12/\n" +
	"\bsettings\x18\x02 \x01(\v2\x13.obb.ClientSettingsR\bsettings\"R\n" +
	"\x19ListClientSettingsRequest\x125\n" +
	"\x17filter_obb_enabled_only\x18\x01 \x01(\bR\x14filterObbEnabledOnly\"\xdd\x01\n" +
	"\x1aListClientSettingsResponse\x12[\n" +
	"\x0fclient_settings\x18\x01 \x03(\v22.obb.ListClientSettingsResponse.ClientSettingsPairR\x0eclientSettings\x1ab\n" +
	"\x12ClientSettingsPair\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12/\n" +
	"\bsettings\x18\x02 \x01(\v2\x13.obb.ClientSettingsR\bsettingsB5\n" +
	"\rcom.oddin.obbZ$github.com/oddin-gg/obbschema/go/obbb\x06proto3"

var (
	file_obb_settings_proto_rawDescOnce sync.Once
	file_obb_settings_proto_rawDescData []byte
)

func file_obb_settings_proto_rawDescGZIP() []byte {
	file_obb_settings_proto_rawDescOnce.Do(func() {
		file_obb_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_obb_settings_proto_rawDesc), len(file_obb_settings_proto_rawDesc)))
	})
	return file_obb_settings_proto_rawDescData
}

var file_obb_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_obb_settings_proto_goTypes = []any{
	(*ClientSettings)(nil),                                // 0: obb.ClientSettings
	(*GetClientSettingsRequest)(nil),                      // 1: obb.GetClientSettingsRequest
	(*GetClientSettingsResponse)(nil),                     // 2: obb.GetClientSettingsResponse
	(*SetClientSettingsRequest)(nil),                      // 3: obb.SetClientSettingsRequest
	(*SetClientSettingsResponse)(nil),                     // 4: obb.SetClientSettingsResponse
	(*ListClientSettingsRequest)(nil),                     // 5: obb.ListClientSettingsRequest
	(*ListClientSettingsResponse)(nil),                    // 6: obb.ListClientSettingsResponse
	(*ListClientSettingsResponse_ClientSettingsPair)(nil), // 7: obb.ListClientSettingsResponse.ClientSettingsPair
}
var file_obb_settings_proto_depIdxs = []int32{
	0, // 0: obb.GetClientSettingsResponse.settings:type_name -> obb.ClientSettings
	0, // 1: obb.SetClientSettingsRequest.settings:type_name -> obb.ClientSettings
	0, // 2: obb.SetClientSettingsResponse.settings:type_name -> obb.ClientSettings
	7, // 3: obb.ListClientSettingsResponse.client_settings:type_name -> obb.ListClientSettingsResponse.ClientSettingsPair
	0, // 4: obb.ListClientSettingsResponse.ClientSettingsPair.settings:type_name -> obb.ClientSettings
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_obb_settings_proto_init() }
func file_obb_settings_proto_init() {
	if File_obb_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_obb_settings_proto_rawDesc), len(file_obb_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_obb_settings_proto_goTypes,
		DependencyIndexes: file_obb_settings_proto_depIdxs,
		MessageInfos:      file_obb_settings_proto_msgTypes,
	}.Build()
	File_obb_settings_proto = out.File
	file_obb_settings_proto_goTypes = nil
	file_obb_settings_proto_depIdxs = nil
}
