// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obb/markets.proto

package com.oddin.obb;

public final class Markets {
  private Markets() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AvailableMarketsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:obb.AvailableMarketsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Event ID URN - e.g "od:match:xx"
     * </pre>
     *
     * <code>string event_urn = 1;</code>
     * @return The eventUrn.
     */
    java.lang.String getEventUrn();
    /**
     * <pre>
     * Event ID URN - e.g "od:match:xx"
     * </pre>
     *
     * <code>string event_urn = 1;</code>
     * @return The bytes for eventUrn.
     */
    com.google.protobuf.ByteString
        getEventUrnBytes();
  }
  /**
   * <pre>
   * AvailableMarketsRequest is used as request for Markets RPC call
   * </pre>
   *
   * Protobuf type {@code obb.AvailableMarketsRequest}
   */
  public static final class AvailableMarketsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:obb.AvailableMarketsRequest)
      AvailableMarketsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AvailableMarketsRequest.newBuilder() to construct.
    private AvailableMarketsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AvailableMarketsRequest() {
      eventUrn_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AvailableMarketsRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.obb.Markets.AvailableMarketsRequest.class, com.oddin.obb.Markets.AvailableMarketsRequest.Builder.class);
    }

    public static final int EVENT_URN_FIELD_NUMBER = 1;
    private volatile java.lang.Object eventUrn_;
    /**
     * <pre>
     * Event ID URN - e.g "od:match:xx"
     * </pre>
     *
     * <code>string event_urn = 1;</code>
     * @return The eventUrn.
     */
    @java.lang.Override
    public java.lang.String getEventUrn() {
      java.lang.Object ref = eventUrn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventUrn_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Event ID URN - e.g "od:match:xx"
     * </pre>
     *
     * <code>string event_urn = 1;</code>
     * @return The bytes for eventUrn.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventUrnBytes() {
      java.lang.Object ref = eventUrn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventUrn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventUrn_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventUrn_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventUrn_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventUrn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.obb.Markets.AvailableMarketsRequest)) {
        return super.equals(obj);
      }
      com.oddin.obb.Markets.AvailableMarketsRequest other = (com.oddin.obb.Markets.AvailableMarketsRequest) obj;

      if (!getEventUrn()
          .equals(other.getEventUrn())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENT_URN_FIELD_NUMBER;
      hash = (53 * hash) + getEventUrn().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.obb.Markets.AvailableMarketsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.obb.Markets.AvailableMarketsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * AvailableMarketsRequest is used as request for Markets RPC call
     * </pre>
     *
     * Protobuf type {@code obb.AvailableMarketsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:obb.AvailableMarketsRequest)
        com.oddin.obb.Markets.AvailableMarketsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.obb.Markets.AvailableMarketsRequest.class, com.oddin.obb.Markets.AvailableMarketsRequest.Builder.class);
      }

      // Construct using com.oddin.obb.Markets.AvailableMarketsRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        eventUrn_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsRequest_descriptor;
      }

      @java.lang.Override
      public com.oddin.obb.Markets.AvailableMarketsRequest getDefaultInstanceForType() {
        return com.oddin.obb.Markets.AvailableMarketsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.obb.Markets.AvailableMarketsRequest build() {
        com.oddin.obb.Markets.AvailableMarketsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.obb.Markets.AvailableMarketsRequest buildPartial() {
        com.oddin.obb.Markets.AvailableMarketsRequest result = new com.oddin.obb.Markets.AvailableMarketsRequest(this);
        result.eventUrn_ = eventUrn_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.obb.Markets.AvailableMarketsRequest) {
          return mergeFrom((com.oddin.obb.Markets.AvailableMarketsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.obb.Markets.AvailableMarketsRequest other) {
        if (other == com.oddin.obb.Markets.AvailableMarketsRequest.getDefaultInstance()) return this;
        if (!other.getEventUrn().isEmpty()) {
          eventUrn_ = other.eventUrn_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                eventUrn_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object eventUrn_ = "";
      /**
       * <pre>
       * Event ID URN - e.g "od:match:xx"
       * </pre>
       *
       * <code>string event_urn = 1;</code>
       * @return The eventUrn.
       */
      public java.lang.String getEventUrn() {
        java.lang.Object ref = eventUrn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventUrn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Event ID URN - e.g "od:match:xx"
       * </pre>
       *
       * <code>string event_urn = 1;</code>
       * @return The bytes for eventUrn.
       */
      public com.google.protobuf.ByteString
          getEventUrnBytes() {
        java.lang.Object ref = eventUrn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventUrn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Event ID URN - e.g "od:match:xx"
       * </pre>
       *
       * <code>string event_urn = 1;</code>
       * @param value The eventUrn to set.
       * @return This builder for chaining.
       */
      public Builder setEventUrn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventUrn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Event ID URN - e.g "od:match:xx"
       * </pre>
       *
       * <code>string event_urn = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventUrn() {
        
        eventUrn_ = getDefaultInstance().getEventUrn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Event ID URN - e.g "od:match:xx"
       * </pre>
       *
       * <code>string event_urn = 1;</code>
       * @param value The bytes for eventUrn to set.
       * @return This builder for chaining.
       */
      public Builder setEventUrnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventUrn_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:obb.AvailableMarketsRequest)
    }

    // @@protoc_insertion_point(class_scope:obb.AvailableMarketsRequest)
    private static final com.oddin.obb.Markets.AvailableMarketsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.obb.Markets.AvailableMarketsRequest();
    }

    public static com.oddin.obb.Markets.AvailableMarketsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AvailableMarketsRequest>
        PARSER = new com.google.protobuf.AbstractParser<AvailableMarketsRequest>() {
      @java.lang.Override
      public AvailableMarketsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AvailableMarketsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AvailableMarketsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.obb.Markets.AvailableMarketsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AvailableMarketsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:obb.AvailableMarketsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    java.util.List<com.oddin.obb.Markets.AvailableMarket> 
        getMarketsList();
    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    com.oddin.obb.Markets.AvailableMarket getMarkets(int index);
    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    int getMarketsCount();
    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    java.util.List<? extends com.oddin.obb.Markets.AvailableMarketOrBuilder> 
        getMarketsOrBuilderList();
    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    com.oddin.obb.Markets.AvailableMarketOrBuilder getMarketsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * AvailableMarketsResponse is used as response for AvailableMarketsRequest RPC call
   * </pre>
   *
   * Protobuf type {@code obb.AvailableMarketsResponse}
   */
  public static final class AvailableMarketsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:obb.AvailableMarketsResponse)
      AvailableMarketsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AvailableMarketsResponse.newBuilder() to construct.
    private AvailableMarketsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AvailableMarketsResponse() {
      markets_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AvailableMarketsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.obb.Markets.AvailableMarketsResponse.class, com.oddin.obb.Markets.AvailableMarketsResponse.Builder.class);
    }

    public static final int MARKETS_FIELD_NUMBER = 1;
    private java.util.List<com.oddin.obb.Markets.AvailableMarket> markets_;
    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.oddin.obb.Markets.AvailableMarket> getMarketsList() {
      return markets_;
    }
    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.oddin.obb.Markets.AvailableMarketOrBuilder> 
        getMarketsOrBuilderList() {
      return markets_;
    }
    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    @java.lang.Override
    public int getMarketsCount() {
      return markets_.size();
    }
    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    @java.lang.Override
    public com.oddin.obb.Markets.AvailableMarket getMarkets(int index) {
      return markets_.get(index);
    }
    /**
     * <pre>
     * List of available markets
     * </pre>
     *
     * <code>repeated .obb.AvailableMarket markets = 1;</code>
     */
    @java.lang.Override
    public com.oddin.obb.Markets.AvailableMarketOrBuilder getMarketsOrBuilder(
        int index) {
      return markets_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < markets_.size(); i++) {
        output.writeMessage(1, markets_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < markets_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, markets_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.obb.Markets.AvailableMarketsResponse)) {
        return super.equals(obj);
      }
      com.oddin.obb.Markets.AvailableMarketsResponse other = (com.oddin.obb.Markets.AvailableMarketsResponse) obj;

      if (!getMarketsList()
          .equals(other.getMarketsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMarketsCount() > 0) {
        hash = (37 * hash) + MARKETS_FIELD_NUMBER;
        hash = (53 * hash) + getMarketsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.obb.Markets.AvailableMarketsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.obb.Markets.AvailableMarketsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * AvailableMarketsResponse is used as response for AvailableMarketsRequest RPC call
     * </pre>
     *
     * Protobuf type {@code obb.AvailableMarketsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:obb.AvailableMarketsResponse)
        com.oddin.obb.Markets.AvailableMarketsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.obb.Markets.AvailableMarketsResponse.class, com.oddin.obb.Markets.AvailableMarketsResponse.Builder.class);
      }

      // Construct using com.oddin.obb.Markets.AvailableMarketsResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (marketsBuilder_ == null) {
          markets_ = java.util.Collections.emptyList();
        } else {
          markets_ = null;
          marketsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.obb.Markets.internal_static_obb_AvailableMarketsResponse_descriptor;
      }

      @java.lang.Override
      public com.oddin.obb.Markets.AvailableMarketsResponse getDefaultInstanceForType() {
        return com.oddin.obb.Markets.AvailableMarketsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.obb.Markets.AvailableMarketsResponse build() {
        com.oddin.obb.Markets.AvailableMarketsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.obb.Markets.AvailableMarketsResponse buildPartial() {
        com.oddin.obb.Markets.AvailableMarketsResponse result = new com.oddin.obb.Markets.AvailableMarketsResponse(this);
        int from_bitField0_ = bitField0_;
        if (marketsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            markets_ = java.util.Collections.unmodifiableList(markets_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.markets_ = markets_;
        } else {
          result.markets_ = marketsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.obb.Markets.AvailableMarketsResponse) {
          return mergeFrom((com.oddin.obb.Markets.AvailableMarketsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.obb.Markets.AvailableMarketsResponse other) {
        if (other == com.oddin.obb.Markets.AvailableMarketsResponse.getDefaultInstance()) return this;
        if (marketsBuilder_ == null) {
          if (!other.markets_.isEmpty()) {
            if (markets_.isEmpty()) {
              markets_ = other.markets_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMarketsIsMutable();
              markets_.addAll(other.markets_);
            }
            onChanged();
          }
        } else {
          if (!other.markets_.isEmpty()) {
            if (marketsBuilder_.isEmpty()) {
              marketsBuilder_.dispose();
              marketsBuilder_ = null;
              markets_ = other.markets_;
              bitField0_ = (bitField0_ & ~0x00000001);
              marketsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMarketsFieldBuilder() : null;
            } else {
              marketsBuilder_.addAllMessages(other.markets_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.oddin.obb.Markets.AvailableMarket m =
                    input.readMessage(
                        com.oddin.obb.Markets.AvailableMarket.parser(),
                        extensionRegistry);
                if (marketsBuilder_ == null) {
                  ensureMarketsIsMutable();
                  markets_.add(m);
                } else {
                  marketsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.oddin.obb.Markets.AvailableMarket> markets_ =
        java.util.Collections.emptyList();
      private void ensureMarketsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          markets_ = new java.util.ArrayList<com.oddin.obb.Markets.AvailableMarket>(markets_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.oddin.obb.Markets.AvailableMarket, com.oddin.obb.Markets.AvailableMarket.Builder, com.oddin.obb.Markets.AvailableMarketOrBuilder> marketsBuilder_;

      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public java.util.List<com.oddin.obb.Markets.AvailableMarket> getMarketsList() {
        if (marketsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(markets_);
        } else {
          return marketsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public int getMarketsCount() {
        if (marketsBuilder_ == null) {
          return markets_.size();
        } else {
          return marketsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public com.oddin.obb.Markets.AvailableMarket getMarkets(int index) {
        if (marketsBuilder_ == null) {
          return markets_.get(index);
        } else {
          return marketsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public Builder setMarkets(
          int index, com.oddin.obb.Markets.AvailableMarket value) {
        if (marketsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarketsIsMutable();
          markets_.set(index, value);
          onChanged();
        } else {
          marketsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public Builder setMarkets(
          int index, com.oddin.obb.Markets.AvailableMarket.Builder builderForValue) {
        if (marketsBuilder_ == null) {
          ensureMarketsIsMutable();
          markets_.set(index, builderForValue.build());
          onChanged();
        } else {
          marketsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public Builder addMarkets(com.oddin.obb.Markets.AvailableMarket value) {
        if (marketsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarketsIsMutable();
          markets_.add(value);
          onChanged();
        } else {
          marketsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public Builder addMarkets(
          int index, com.oddin.obb.Markets.AvailableMarket value) {
        if (marketsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarketsIsMutable();
          markets_.add(index, value);
          onChanged();
        } else {
          marketsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public Builder addMarkets(
          com.oddin.obb.Markets.AvailableMarket.Builder builderForValue) {
        if (marketsBuilder_ == null) {
          ensureMarketsIsMutable();
          markets_.add(builderForValue.build());
          onChanged();
        } else {
          marketsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public Builder addMarkets(
          int index, com.oddin.obb.Markets.AvailableMarket.Builder builderForValue) {
        if (marketsBuilder_ == null) {
          ensureMarketsIsMutable();
          markets_.add(index, builderForValue.build());
          onChanged();
        } else {
          marketsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public Builder addAllMarkets(
          java.lang.Iterable<? extends com.oddin.obb.Markets.AvailableMarket> values) {
        if (marketsBuilder_ == null) {
          ensureMarketsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, markets_);
          onChanged();
        } else {
          marketsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public Builder clearMarkets() {
        if (marketsBuilder_ == null) {
          markets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          marketsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public Builder removeMarkets(int index) {
        if (marketsBuilder_ == null) {
          ensureMarketsIsMutable();
          markets_.remove(index);
          onChanged();
        } else {
          marketsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public com.oddin.obb.Markets.AvailableMarket.Builder getMarketsBuilder(
          int index) {
        return getMarketsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public com.oddin.obb.Markets.AvailableMarketOrBuilder getMarketsOrBuilder(
          int index) {
        if (marketsBuilder_ == null) {
          return markets_.get(index);  } else {
          return marketsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public java.util.List<? extends com.oddin.obb.Markets.AvailableMarketOrBuilder> 
           getMarketsOrBuilderList() {
        if (marketsBuilder_ != null) {
          return marketsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(markets_);
        }
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public com.oddin.obb.Markets.AvailableMarket.Builder addMarketsBuilder() {
        return getMarketsFieldBuilder().addBuilder(
            com.oddin.obb.Markets.AvailableMarket.getDefaultInstance());
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public com.oddin.obb.Markets.AvailableMarket.Builder addMarketsBuilder(
          int index) {
        return getMarketsFieldBuilder().addBuilder(
            index, com.oddin.obb.Markets.AvailableMarket.getDefaultInstance());
      }
      /**
       * <pre>
       * List of available markets
       * </pre>
       *
       * <code>repeated .obb.AvailableMarket markets = 1;</code>
       */
      public java.util.List<com.oddin.obb.Markets.AvailableMarket.Builder> 
           getMarketsBuilderList() {
        return getMarketsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.oddin.obb.Markets.AvailableMarket, com.oddin.obb.Markets.AvailableMarket.Builder, com.oddin.obb.Markets.AvailableMarketOrBuilder> 
          getMarketsFieldBuilder() {
        if (marketsBuilder_ == null) {
          marketsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.oddin.obb.Markets.AvailableMarket, com.oddin.obb.Markets.AvailableMarket.Builder, com.oddin.obb.Markets.AvailableMarketOrBuilder>(
                  markets_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          markets_ = null;
        }
        return marketsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:obb.AvailableMarketsResponse)
    }

    // @@protoc_insertion_point(class_scope:obb.AvailableMarketsResponse)
    private static final com.oddin.obb.Markets.AvailableMarketsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.obb.Markets.AvailableMarketsResponse();
    }

    public static com.oddin.obb.Markets.AvailableMarketsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AvailableMarketsResponse>
        PARSER = new com.google.protobuf.AbstractParser<AvailableMarketsResponse>() {
      @java.lang.Override
      public AvailableMarketsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AvailableMarketsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AvailableMarketsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.obb.Markets.AvailableMarketsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AvailableMarketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:obb.AvailableMarket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The ID using the same values as our odds feed in XML.
     * </pre>
     *
     * <code>uint32 market_id = 1;</code>
     * @return The marketId.
     */
    int getMarketId();

    /**
     * <pre>
     * The specifier is using the same values as our odds feed in XML.
     * e.g. "variant=way:three|way=three|map=1"
     * </pre>
     *
     * <code>string specifiers = 2;</code>
     * @return The specifiers.
     */
    java.lang.String getSpecifiers();
    /**
     * <pre>
     * The specifier is using the same values as our odds feed in XML.
     * e.g. "variant=way:three|way=three|map=1"
     * </pre>
     *
     * <code>string specifiers = 2;</code>
     * @return The bytes for specifiers.
     */
    com.google.protobuf.ByteString
        getSpecifiersBytes();
  }
  /**
   * Protobuf type {@code obb.AvailableMarket}
   */
  public static final class AvailableMarket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:obb.AvailableMarket)
      AvailableMarketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AvailableMarket.newBuilder() to construct.
    private AvailableMarket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AvailableMarket() {
      specifiers_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AvailableMarket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oddin.obb.Markets.internal_static_obb_AvailableMarket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oddin.obb.Markets.internal_static_obb_AvailableMarket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oddin.obb.Markets.AvailableMarket.class, com.oddin.obb.Markets.AvailableMarket.Builder.class);
    }

    public static final int MARKET_ID_FIELD_NUMBER = 1;
    private int marketId_;
    /**
     * <pre>
     * The ID using the same values as our odds feed in XML.
     * </pre>
     *
     * <code>uint32 market_id = 1;</code>
     * @return The marketId.
     */
    @java.lang.Override
    public int getMarketId() {
      return marketId_;
    }

    public static final int SPECIFIERS_FIELD_NUMBER = 2;
    private volatile java.lang.Object specifiers_;
    /**
     * <pre>
     * The specifier is using the same values as our odds feed in XML.
     * e.g. "variant=way:three|way=three|map=1"
     * </pre>
     *
     * <code>string specifiers = 2;</code>
     * @return The specifiers.
     */
    @java.lang.Override
    public java.lang.String getSpecifiers() {
      java.lang.Object ref = specifiers_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        specifiers_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The specifier is using the same values as our odds feed in XML.
     * e.g. "variant=way:three|way=three|map=1"
     * </pre>
     *
     * <code>string specifiers = 2;</code>
     * @return The bytes for specifiers.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSpecifiersBytes() {
      java.lang.Object ref = specifiers_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        specifiers_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (marketId_ != 0) {
        output.writeUInt32(1, marketId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(specifiers_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, specifiers_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (marketId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, marketId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(specifiers_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, specifiers_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.oddin.obb.Markets.AvailableMarket)) {
        return super.equals(obj);
      }
      com.oddin.obb.Markets.AvailableMarket other = (com.oddin.obb.Markets.AvailableMarket) obj;

      if (getMarketId()
          != other.getMarketId()) return false;
      if (!getSpecifiers()
          .equals(other.getSpecifiers())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MARKET_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMarketId();
      hash = (37 * hash) + SPECIFIERS_FIELD_NUMBER;
      hash = (53 * hash) + getSpecifiers().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.oddin.obb.Markets.AvailableMarket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.oddin.obb.Markets.AvailableMarket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.oddin.obb.Markets.AvailableMarket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code obb.AvailableMarket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:obb.AvailableMarket)
        com.oddin.obb.Markets.AvailableMarketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oddin.obb.Markets.internal_static_obb_AvailableMarket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oddin.obb.Markets.internal_static_obb_AvailableMarket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.oddin.obb.Markets.AvailableMarket.class, com.oddin.obb.Markets.AvailableMarket.Builder.class);
      }

      // Construct using com.oddin.obb.Markets.AvailableMarket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        marketId_ = 0;

        specifiers_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oddin.obb.Markets.internal_static_obb_AvailableMarket_descriptor;
      }

      @java.lang.Override
      public com.oddin.obb.Markets.AvailableMarket getDefaultInstanceForType() {
        return com.oddin.obb.Markets.AvailableMarket.getDefaultInstance();
      }

      @java.lang.Override
      public com.oddin.obb.Markets.AvailableMarket build() {
        com.oddin.obb.Markets.AvailableMarket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.oddin.obb.Markets.AvailableMarket buildPartial() {
        com.oddin.obb.Markets.AvailableMarket result = new com.oddin.obb.Markets.AvailableMarket(this);
        result.marketId_ = marketId_;
        result.specifiers_ = specifiers_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oddin.obb.Markets.AvailableMarket) {
          return mergeFrom((com.oddin.obb.Markets.AvailableMarket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.oddin.obb.Markets.AvailableMarket other) {
        if (other == com.oddin.obb.Markets.AvailableMarket.getDefaultInstance()) return this;
        if (other.getMarketId() != 0) {
          setMarketId(other.getMarketId());
        }
        if (!other.getSpecifiers().isEmpty()) {
          specifiers_ = other.specifiers_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                marketId_ = input.readUInt32();

                break;
              } // case 8
              case 18: {
                specifiers_ = input.readStringRequireUtf8();

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int marketId_ ;
      /**
       * <pre>
       * The ID using the same values as our odds feed in XML.
       * </pre>
       *
       * <code>uint32 market_id = 1;</code>
       * @return The marketId.
       */
      @java.lang.Override
      public int getMarketId() {
        return marketId_;
      }
      /**
       * <pre>
       * The ID using the same values as our odds feed in XML.
       * </pre>
       *
       * <code>uint32 market_id = 1;</code>
       * @param value The marketId to set.
       * @return This builder for chaining.
       */
      public Builder setMarketId(int value) {
        
        marketId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The ID using the same values as our odds feed in XML.
       * </pre>
       *
       * <code>uint32 market_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMarketId() {
        
        marketId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object specifiers_ = "";
      /**
       * <pre>
       * The specifier is using the same values as our odds feed in XML.
       * e.g. "variant=way:three|way=three|map=1"
       * </pre>
       *
       * <code>string specifiers = 2;</code>
       * @return The specifiers.
       */
      public java.lang.String getSpecifiers() {
        java.lang.Object ref = specifiers_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          specifiers_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The specifier is using the same values as our odds feed in XML.
       * e.g. "variant=way:three|way=three|map=1"
       * </pre>
       *
       * <code>string specifiers = 2;</code>
       * @return The bytes for specifiers.
       */
      public com.google.protobuf.ByteString
          getSpecifiersBytes() {
        java.lang.Object ref = specifiers_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          specifiers_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The specifier is using the same values as our odds feed in XML.
       * e.g. "variant=way:three|way=three|map=1"
       * </pre>
       *
       * <code>string specifiers = 2;</code>
       * @param value The specifiers to set.
       * @return This builder for chaining.
       */
      public Builder setSpecifiers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        specifiers_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The specifier is using the same values as our odds feed in XML.
       * e.g. "variant=way:three|way=three|map=1"
       * </pre>
       *
       * <code>string specifiers = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpecifiers() {
        
        specifiers_ = getDefaultInstance().getSpecifiers();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The specifier is using the same values as our odds feed in XML.
       * e.g. "variant=way:three|way=three|map=1"
       * </pre>
       *
       * <code>string specifiers = 2;</code>
       * @param value The bytes for specifiers to set.
       * @return This builder for chaining.
       */
      public Builder setSpecifiersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        specifiers_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:obb.AvailableMarket)
    }

    // @@protoc_insertion_point(class_scope:obb.AvailableMarket)
    private static final com.oddin.obb.Markets.AvailableMarket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.oddin.obb.Markets.AvailableMarket();
    }

    public static com.oddin.obb.Markets.AvailableMarket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AvailableMarket>
        PARSER = new com.google.protobuf.AbstractParser<AvailableMarket>() {
      @java.lang.Override
      public AvailableMarket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AvailableMarket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AvailableMarket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.oddin.obb.Markets.AvailableMarket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_obb_AvailableMarketsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_obb_AvailableMarketsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_obb_AvailableMarketsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_obb_AvailableMarketsResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_obb_AvailableMarket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_obb_AvailableMarket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021obb/markets.proto\022\003obb\",\n\027AvailableMar" +
      "ketsRequest\022\021\n\tevent_urn\030\001 \001(\t\"A\n\030Availa" +
      "bleMarketsResponse\022%\n\007markets\030\001 \003(\0132\024.ob" +
      "b.AvailableMarket\"8\n\017AvailableMarket\022\021\n\t" +
      "market_id\030\001 \001(\r\022\022\n\nspecifiers\030\002 \001(\tB\035\n\rc" +
      "om.oddin.obbZ\014oddin.gg/obbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_obb_AvailableMarketsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_obb_AvailableMarketsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_obb_AvailableMarketsRequest_descriptor,
        new java.lang.String[] { "EventUrn", });
    internal_static_obb_AvailableMarketsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_obb_AvailableMarketsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_obb_AvailableMarketsResponse_descriptor,
        new java.lang.String[] { "Markets", });
    internal_static_obb_AvailableMarket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_obb_AvailableMarket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_obb_AvailableMarket_descriptor,
        new java.lang.String[] { "MarketId", "Specifiers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
