// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obb/service.proto

package com.oddin.obb;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021obb/service.proto\022\003obb\032\021obb/markets.pr" +
      "oto\032\021obb/popular.proto\032\021obb/session.prot" +
      "o2\267\002\n\003obb\022O\n\020AvailableMarkets\022\034.obb.Avai" +
      "lableMarketsRequest\032\035.obb.AvailableMarke" +
      "tsResponse\022F\n\rSessionCreate\022\031.obb.Sessio" +
      "nCreateRequest\032\032.obb.SessionCreateRespon" +
      "se\022@\n\013SessionInfo\022\027.obb.SessionInfoReque" +
      "st\032\030.obb.SessionInfoResponse\022U\n\022PopularC" +
      "ombination\022\036.obb.PopularCombinationReque" +
      "st\032\037.obb.PopularCombinationResponseB5\n\rc" +
      "om.oddin.obbZ$github.com/oddin-gg/obbsch" +
      "ema/go/obbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.oddin.obb.Markets.getDescriptor(),
          com.oddin.obb.Popular.getDescriptor(),
          com.oddin.obb.Session.getDescriptor(),
        });
    com.oddin.obb.Markets.getDescriptor();
    com.oddin.obb.Popular.getDescriptor();
    com.oddin.obb.Session.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
