// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obb/service.proto

package com.oddin.obb;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021obb/service.proto\022\003obb\032\021obb/markets.pr" +
      "oto\032\021obb/session.proto\032\021obb/popular.prot" +
      "o2\313\001\n\003obb\0222\n\007Markets\022\022.obb.MarketRequest" +
      "\032\023.obb.MarketResponse\0228\n\007Session\022\023.obb.S" +
      "essionRequest\032\024.obb.SessionResponse(\0010\001\022" +
      "V\n\023PopularCombinations\022\036.obb.PopularComb" +
      "inationRequest\032\037.obb.PopularCombinationR" +
      "esponseB\035\n\rcom.oddin.obbZ\014oddin.gg/obbb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.oddin.obb.Markets.getDescriptor(),
          com.oddin.obb.Session.getDescriptor(),
          com.oddin.obb.Popular.getDescriptor(),
        });
    com.oddin.obb.Markets.getDescriptor();
    com.oddin.obb.Session.getDescriptor();
    com.oddin.obb.Popular.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
